# Generated by Django 4.0.3 on 2023-09-30 02:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Job', max_length=255)),
                ('description', models.TextField(help_text='Description of the Job')),
                ('estimated_time', models.DurationField(help_text='Estimated Time to complete the Job')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Vehicle', max_length=255)),
                ('make', models.CharField(help_text='Make of the Vehicle', max_length=255)),
                ('model', models.CharField(help_text='Model of the Vehicle', max_length=255)),
                ('year', models.PositiveIntegerField(help_text='Manufacturing Year of the Vehicle', validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2023)])),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Tool', max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='projects.job')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Part', max_length=255)),
                ('part_number', models.CharField(blank=True, help_text='Part Number if available', max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='projects.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.vehicle'),
        ),
    ]
